const router = require('express').Router();
const multer = require('multer');
const upload = multer();
const ctrl = require('../controllers/scholarshipController');
const auth = require('../middleware/auth');
const role = require('../middleware/role');
router.post('/', auth, role(['admin']), ctrl.createScholarship);
router.post('/apply', auth, upload.single('file'), ctrl.apply);
router.get('/:id/results', auth, role(['admin']), ctrl.resultList);
module.exports = router;
